# -*- coding: utf-8 -*-
"""Notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/AI-Core/Content-Public/blob/main/Content/units/Cloud-and-DevOps/3.%20Essential%20Cloud%20Technology/0.%20What%20is%20AWS%3F/Notebook.ipynb

# AWS Overview

First of all, we need to go to the AWS console and create a new account. To do this, go to the [AWS Console](https://console.aws.amazon.com/console/home), and create a new account. You will need a credit card to pay for the AWS services, but worry not! You can use a free service tier.

Once created, go to the [AWS Console](https://console.aws.amazon.com/console/home) and select the Services tab. You will see a list of services that are available

![](https://github.com/AI-Core/Content-Public/blob/main/Content/units/Cloud-and-DevOps/3.%20Essential%20Cloud%20Technology/0.%20What%20is%20AWS%3F/images/AWS_Services.png?raw=1)

There are plenty of services in AWS, you can even manage your satellite server in the cloud! We only have bugdet for providing a few satellites, so instead, in this introduction we will focus on :

- [Amazon RDS](https://aws.amazon.com/rds/) - Relational Database Service
- [Amazon S3](https://aws.amazon.com/s3/) - Simple Storage Service
- [Amazon EC2](https://aws.amazon.com/ec2/) - Elastic Compute Cloud
"""