# -*- coding: utf-8 -*-
"""Notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/AI-Core/Content-Public/blob/main/Content/units/Data-Handling/3.%20SQL/2.%20SQL%20Basics/Notebook.ipynb

# SQL - Basics

Many of the lessons in this module are presented in slides. 

Click here to open the presentation in [PDF format](https://aicore-files.s3.amazonaws.com/Data-Eng/SQL/1.+SQL+Basics.pdf)

Click here to open the presentation in [Keynote format](https://aicore-files.s3.amazonaws.com/Data-Eng/SQL/1.+SQL+Basics.key)

Click here to open the presentation in [Powerpoint format](https://aicore-files.s3.amazonaws.com/Data-Eng/SQL/1.+SQL+Basics.pptx)
"""