# -*- coding: utf-8 -*-
"""Notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/AI-Core/Content-Public/blob/main/Content/units/Data-Handling/3.%20SQL/3.%20CRUD/Notebook.ipynb

# SQL - CRUD

Many of the lessons in this module are presented in slides. 

Click here to open the presentation in [PDF format](https://aicore-files.s3.amazonaws.com/Data-Eng/SQL/2.+SQL+CRUD.pdf)

Click here to open the presentation in [Keynote format](https://aicore-files.s3.amazonaws.com/Data-Eng/SQL/2.+SQL+CRUD.key)

Click here to open the presentation in [Powerpoint format](https://aicore-files.s3.amazonaws.com/Data-Eng/SQL/2.+SQL+CRUD.pptx)
"""